# Generated by Django 2.1.5 on 2019-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Id', models.CharField(max_length=40)),
                ('user_Loc', models.IntegerField()),
                ('user_ModList', models.CharField(max_length=40)),
            ],
        ),
    ]
